### PR TITLE
Check spacing of function declarations

### LINKED ISSUE #412: Parameters in functions declarations are not forced to be padded with space
One of the WordPress standards is to pad functions/methods parameters with spaces, before and after.

The sniffer correctly screams about missing spaces in the following example:
```
test(7, 'cat');
```

But the rule seems to be ignored for functions and methods declarations, this is incorrectly not marked as invalid:
```
function test($param1, $param2) {
    ...
}
```

### PR DESCRIPTION
**Pull request by JDGrimes**
This adds functions and closures to the control structure spacing
sniff. The sniff checks for proper spacing on each side of each of the
parentheses. It also checks that the opening brace is on the same line.

I’ve actually improved the sniff while I was at it, to check for excess
space in addition to insufficient space.

Because of these improvements, and due to the non-configurability of
the upstream version of this sniff, this sniff is really not a
duplicate, and so #385 can be closed.

I’ve also removed our implementation of the `FunctionDeclarationArgumentSpacing` sniff in favor of the upstream version. This is some overlap between that sniff and this one, but that one only checks the spacing of the arguments.

Fixes #412, #385

### CODE REVIEW

File: WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php [hunk 1]
```diff
@@ -188,22 +254,45 @@ public function process(PHP_CodeSniffer_File $phpcsFile, $stackPtr)
...
+	                        $phpcsFile->fixer->beginChangeset();
+	                        $phpcsFile->fixer->addContentBefore($parenthesisCloser, ' ');
+	                        $phpcsFile->fixer->endChangeset();
+	                    }
+	                } else {
+	                    $phpcsFile->addError($error, $parenthesisCloser, 'NoSpaceBeforeCloseParenthesis');
+	                }
+	            }
+
+		        if (
```
Comment (GaryJones) [inline WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php]: This block seems to be indented one level too many?

File: WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.inc [hunk 2]
```diff
@@ -45,3 +45,31 @@ endif;
 if ( false ) :
 else :
 endif;
+
+function($arg){} // Bad
+function ( $arg ) {
```
Comment (GaryJones) [inline WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.inc]: WPCS for PHP doesn't actually specify a space before `(` or not for closures simply because they aren't being used in core. For WPCS for JS, a space should not be added, but for PSR-2, a space is needed. The powers that be may go either way - stay inline with the JS, or follow PSR-2.

----

Can checks for `use ()` be added too? e.g.

~~~php
$closureWithArgsAndVars = function ( $arg1, $arg2 ) use ( $var1, $var2 ) {}; // OK

$closureWithArgsAndVars = function ( $arg1, $arg2 ) use( $var1, $var2 ) {}; // Bad, no space before open parenthesis prohibited.
$closureWithArgsAndVars = function ( $arg1, $arg2 ) use  ( $var1, $var2 ) {}; // Bad, expected exactly one space before opening parenthesis.

$closureWithArgsAndVars = function ( $arg1, $arg2 ) use ( $var1, $var2) {}; // Bad, no space before closing parenthesis prohibited
$closureWithArgsAndVars = function ( $arg1, $arg2 ) use ( $var1, $var2  ) {}; // Bad, expected exactly one space before closing parenthesis

$closureWithArgsAndVars = function ( $arg1, $arg2 ) use ($var1, $var2 ) {}; // Bad, no space after open parenthesis prohibited
$closureWithArgsAndVars = function ( $arg1, $arg2 ) use (  $var1, $var2 ) {}; // Bad, expected exactly one space after opening parenthesis

$closureWithArgsAndVars = function ( $arg1, $arg2 ) use ( $var1, $var2 ){}; // Bad, space between closing parenthesis and control structure required.
$closureWithArgsAndVars = function ( $arg1, $arg2 ) use ( $var1, $var2 )  {}; // Bad, expected exactly one space between closing parenthesis and control structure.
~~~

Comment (JDGrimes) [inline WordPress/Tests/WhiteSpace/ControlStructureSpacingUnitTest.inc]: Some of those are already fixed by other sniffs.

`WordPress.WhiteSpace.ControlStructureSpacing.NoSpaceAfterStructureOpen` fixes this:

```php
$closureWithArgsAndVars = function ( $arg1, $arg2 ) use( $var1, $var2 ) {}; // Bad, no space before open parenthesis prohibited.
```
`Squiz.Functions.FunctionDeclarationArgumentSpacing.SpacingBeforeClose` fixes these:

```php
$closureWithArgsAndVars = function ( $arg1, $arg2 ) use ( $var1, $var2) {}; // Bad, no space before closing parenthesis prohibited
$closureWithArgsAndVars = function ( $arg1, $arg2 ) use ( $var1, $var2  ) {}; // Bad, expected exactly one space before closing parenthesis
```
`Squiz.Functions.FunctionDeclarationArgumentSpacing.SpacingAfterOpen` fixes these:

```php
$closureWithArgsAndVars = function ( $arg1, $arg2 ) use ($var1, $var2 ) {}; // Bad, no space after open parenthesis prohibited
$closureWithArgsAndVars = function ( $arg1, $arg2 ) use (  $var1, $var2 ) {}; // Bad, expected exactly one space after opening parenthesis
```

Additionally, `WordPress.WhiteSpace.ControlStructureSpacing.ExtraSpaceAfterCloseParenthesis` fixes this:

```php
$closureWithArgsAndVars = function ( $arg1, $arg2 )  use ( $var1, $var2 ) {}; // Bad, expected exactly one space between closing parenthesis and control structure.
```
`WordPress.WhiteSpace.ControlStructureSpacing.NoSpaceAfterCloseParenthesis` attempts to fix this, however it fails, producing the second line instead:

```php
$closureWithArgsAndVars = function ( $arg1, $arg2 )use ( $var1, $var2 ) {}; // Bad, expected exactly one space between closing parenthesis and control structure.
$closureWithArgsAndVars = function ( $arg1, $arg2 )use ( $var1, $var2 )    {}; // Bad, expected exactly one space between closing parenthesis and control structure.
```

That leaves these:

```php
$closureWithArgsAndVars = function ( $arg1, $arg2 ) use  ( $var1, $var2 ) {}; // Bad, expected exactly one space before opening parenthesis.

$closureWithArgsAndVars = function ( $arg1, $arg2 ) use ( $var1, $var2 ){}; // Bad, space between closing parenthesis and control structure required.
$closureWithArgsAndVars = function ( $arg1, $arg2 ) use ( $var1, $var2 )  {}; // Bad, expected exactly one space between closing parenthesis and control structure.
```

**Comment by JDGrimes** [comment]
I've updated this:
- Handling for `use` statements in 7d19272.
- Allow closure spacing to be configured to be either 1 or 0 spaces before the opening parenthesis (c7276e3).
- I left the indentation, just because I didn't feel like fixing it. It's a tabs vs spaces thing, and there are so many places where it is messed up that the best thing would be to just convert the whole file to tabs. But that is for another pull request.

**Comment by GaryJones** [comment]
Excellent work, thanks @JDGrimes!
