### PR TITLE
WP.I18n: Fix false positive on method calls.

### LINKED ISSUE #1266: False positive for Missing $domain arg
I activated the text domain verification with:
```
<rule ref="WordPress.WP.I18n">
	<properties>
		<property name="text_domain" type="array" value="polylang" />
	</properties>
</rule>
```
and excluded the `WordPress.WP.I18n.LowLevelTranslationFunction` sniff.

However the code
`$mo->translate( $string )`
generates an error: `Missing $domain arg. (WordPress.WP.I18n.MissingArgDomain)`.

I would expect this error for a missing domain in a call to `__()` or any high level I18n functions, but the `translate` method of the `Translations` WordPress class doesn't have any domain argument. See: https://github.com/WordPress/WordPress/blob/4.9.1/wp-includes/pomo/translations.php#L94-L98, so I don't expect that using a `translate` method with only one argument would generate such error.

I am using PHPCS 2.9.1 and WPCS 0.14.

### PR DESCRIPTION
**Pull request by jrfnl**
The `WP.I18n` sniff did not properly verify whether the `T_STRING` found was actually a function call, in contrast to a method call or a namespaced function call.

I've fixed this now by extending the `AbstractFunctionRestriction` sniff and using the logic contained therein to make sure that only plain function calls are being addressed.

Includes unit tests.

A future further improvement could be extending the `AbstractFunctionParameter` sniff instead to benefit from using the logic from the `get_function_call_parameters()` utility function.

For now, I've just made the function parenthesis check slightly more stable, by making it code style independent and adding an extra safeguard for live coding situations.

Fixes #1266

### CODE REVIEW

File: WordPress/Sniffs/WP/I18nSniff.php [hunk 1]
```diff
@@ -185,21 +202,40 @@ public function process_token( $stack_ptr ) {
 			}
 		}
 
-		if ( '_' === $token['content'] ) {
+		// Prevent exclusion of the i18n group.
+		$this->exclude = '';
+
+		// Note: this will give false positives if a method called `_` is used.
+		if ( '_' === $this->tokens[ $stack_ptr ]['content'] ) {
```
Comment (JDGrimes) [inline WordPress/Sniffs/WP/I18nSniff.php]: Is there a particular reason not to move this check as well, other than the fact that `_` isn't a part of the `i18n` group? Couldn't it be added as part of a second group and checked in the `process_matched_token()` method? That way it wouldn't catch false-positives from `_()` methods either. (Which admittedly seems unlikely, but I see no reason not to exclude that possibility.)

Comment (jrfnl) [reply WordPress/Sniffs/WP/I18nSniff.php]: > Is there a particular reason not to move this check as well, other than the fact that _ isn't a part of the i18n group?

I didn't move for exactly that reason :grin: 

> Couldn't it be added as part of a second group and checked in the process_matched_token() method? That way it wouldn't catch false-positives from _() methods either.

I think there are more elegant ways to do this, I'll have a fiddle with it.

Comment (jrfnl) [reply WordPress/Sniffs/WP/I18nSniff.php]: Reading your comment again, I now understand what you mean by "second group". Yes, that would actually work perfectly. Changing things now.

Comment (jrfnl) [reply WordPress/Sniffs/WP/I18nSniff.php]: Done. Added second commit. Feel free to squash on merge.

I've also moved the other check which checks for a particular function down to below the parenthesis check as an extra safeguard against false positives.
